# This is non portable template that means we are specified 
# image id that belongs us-east-1 ami id. You can create only
# in the us-east-1 region

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'accatpics171414' # give uniq bucket name
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: 'A4L'
      InstanceType: 't2.micro'
      ImageId: 'ami-0f9fc25dd2506cf6d' 